name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  sonar_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  deploy_staging:
    runs-on: ubuntu-latest
    needs: sonar_analysis
    steps:
      - name: Deploy to Staging
        run: |
          docker-compose -f docker-compose.yml up -d --build
